title: Hannah Wambui Kinyanjui
#logo: image path /assets/img/headshot_circle.img
description: Data scientist | ETL | M&E | Dashboad developer | Project Manager
show_downloads: False
theme: jekyll-them-minimal
